version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
#    volumes:
#      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - db_demo
    command:
      [ 'start', '8000' ]

  db:
    image: postgres:15
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=service
      - POSTGRES_PASSWORD=qwerty

  db_demo:
    build:
      context: .
      dockerfile: ./demo.dockerfile
    restart: always
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty